### ISSUE TITLE
add github actions

### ISSUE THREAD

**Issue by georgettica** [ellisonleao/vl#12]
I am using vl and it has not updated for a long while now.

I want to make sure it keeps up to date and doesn't get a vuln in it.

so I added GHA for it on my fork

**Comment by ellisonleao** [comment]
hey @georgettica , please check the [Running in a github action](https://github.com/ellisonleao/vl#running-in-a-github-action) section for how to setup the gh action

**Comment by georgettica** [comment]
yeah, this seems fair :)
I meant more on adding GHA to this repo to allow for security upgrades and testing

**Comment by ellisonleao** [comment]
Makes sense! will check it out
